export const SubCategory = [
  { label: "Điện thoại", value: "Điện thoại" },
  { label: "Máy tính bảng", value: "Máy tính bảng" },
  { label: "Pin dự phòng", value: "Pin dự phòng" },
  { label: "Bộ sạc", value: "Bộ sạc" },
  {
    label: "Ốp lưng",
    value: "Ốp lưng",
  },
  { label: "Kính cường lực", value: "Kính cường lực" },
  { label: "Thẻ nhớ, sim", value: "Thẻ nhớ, sim" },
  { label: "Tai nghe", value: "Tai nghe" },
  { label: "Phụ Kiện Khác", value: "Phụ Kiện Khác" },
  { label: "Tivi", value: "Tivi" },
  { label: "Loa Bluetooth", value: "Loa Bluetooth" },
  { label: "Tủ lạnh", value: "Tủ lạnh" },
  { label: "Máy giặt", value: "Máy giặt" },
  {
    label: "Máy hút bụi & Thiết bị làm sạch",
    value: "Máy hút bụi & Thiết bị làm sạch",
  },
  { label: "Đồ gia dụng nhà bếp", value: "Đồ gia dụng nhà bếp" },
  { label: "Thiết bị chăm sóc quần áo", value: "Thiết bị chăm sóc quần áo" },
  { label: "Quạt & Máy nóng lạnh", value: "Quạt & Máy nóng lạnh" },
  { label: "Đồ dùng nhà bếp", value: "Đồ dùng nhà bếp" },
  { label: "Gaming Laptop", value: "Gaming Laptop" },
  { label: "Đồng hồ nam", value: "Đồng hồ nam" },
  { label: "Đồng hồ nữ", value: "Đồng hồ nữ" },
  { label: "Đồng hồ Unisex", value: "Đồng hồ Unisex" },
  { label: "Vali", value: "Vali" },
  { label: "Giày thể thao", value: "Giày thể thao" },
  { label: "Túi du lịch", value: "Túi du lịch" },
  { label: "Thời trang thể thao", value: "Thời trang thể thao" },
  { label: "Dụng cụ thể thao", value: "Dụng cụ thể thao" },
  { label: "Phụ kiện thể thao", value: "Phụ kiện thể thao" },
  { label: "Tã em bé", value: "Tã em bé" },
  { label: "Chăm sóc sức khỏe bé", value: "Chăm sóc sức khỏe bé" },
  { label: "Sữa", value: "Sữa" },
  {
    label: "Chăm sóc nhà cửa và giặt ủi",
    value: "Chăm sóc nhà cửa và giặt ủi",
  },
  { label: "Chăm sóc da mặt", value: "Chăm sóc da mặt" },
  { label: "Sản phẩm trang điểm", value: "Sản phẩm trang điểm" },
  { label: "Chăm sóc môi", value: "Chăm sóc môi" },
  { label: "Mặt nạ chăm sóc da", value: "Mặt nạ chăm sóc da" },
  { label: "Thực phẩm chức năng", value: "Thực phẩm chức năng" },
  { label: "Tiểu thuyết", value: "Tiểu thuyết" },
  {
    label: "Sách Tâm lý & Phát triển bản thân",
    value: "Sách Tâm lý & Phát triển bản thân",
  },
  { label: "Truyện tranh", value: "Truyện tranh" },
  { label: "Balo đựng laptop", value: "Balo đựng laptop" },
  { label: "Túi đeo chéo", value: "Túi đeo chéo" },
  { label: "Thức ăn cho chó", value: "Thức ăn cho chó" },
  { label: "Thức ăn cho mèo", value: "Thức ăn cho mèo" },
  { label: "Nhẫn", value: "Nhẫn" },
  { label: "Bông tai", value: "Bông tai" },
  { label: "Mặt dây chuyền", value: "Mặt dây chuyền" },
  { label: "Lắc tay", value: "Lắc tay" },
  { label: "Vòng tay", value: "Vòng tay" },
];
